apiVersion: v1
kind: ConfigMap
metadata:
  name: mongocm
data:
  db_username: devdb
  db_hostname: mongo

---
apiVersion: v1
kind: Secret
metadata:
  name: mongosec
type: Opaque
data:
  db_password: ZGV2ZGJAMTIz

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sbdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sbapp
  template: #template for the pod
    metadata:
      name: sbdatabase
      labels:
        app: sbapp
    spec:
      containers:
      - name: mongodatabase-container
        image: benadabankah/spring-boot-mongo
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongosec
              key: db_password
        - name: MONGO_DB_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: mongocm
              key: db_hostname
        - name: MONGO_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mongocm
              key: db_username

---
apiVersion: v1
kind: Service
metadata:
  name: mongolb
spec:
  selector:
    app: sbapp
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sb-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodbrs
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
     metadata:
       name: mongodbpod
       labels:
         app: mongodb
     spec:
       volumes:
       - name: pvc
         persistentVolumeClaim:
           claimName: sb-pvc
       containers:
       - name: mongodbcontainer
         image: mongo
         ports:
         - containerPort: 27017
         env:
         - name: MONGO_INITDB_ROOT_USERNAME
           valueFrom:
             configMapKeyRef:
               name: mongocm
               key: db_username
         - name: MONGO_INITDB_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: mongosec
               key: db_password
         volumeMounts:
         - name: pvc
           mountPath: /data/db
---

apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017